# Parameter list with default values

/**:                       
  ros_parameters:
    n_multi_agent: 2            # Size of the fleet: [1 to 3]
    debug_rov: 0                # Output in terminal: [0 or 1] for Setpoint publishing, [2 to 4] for output from IPOPT for ROV2 to ROV4
    FOV_range_deg: 60.0         # Hard constraint on Field of View angle in degrees: [Float]

